/* tslint:disable */
/* eslint-disable */
/**
 * OptProv API
 * This is the REST API to interact and control with libp2p hosts. All responses not in the HTTP status code range [200,300) return the error object below. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProvidersRequest
 */
export interface GetProvidersRequest {
    /**
     * Peer ID of the remote peer.
     * @type {string}
     * @memberof GetProvidersRequest
     */
    remoteId: string;
    /**
     * The CID that should be asked for.
     * @type {string}
     * @memberof GetProvidersRequest
     */
    contentId: string;
}

export function GetProvidersRequestFromJSON(json: any): GetProvidersRequest {
    return GetProvidersRequestFromJSONTyped(json, false);
}

export function GetProvidersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProvidersRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'remoteId': json['remoteId'],
        'contentId': json['contentId'],
    };
}

export function GetProvidersRequestToJSON(value?: GetProvidersRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'remoteId': value.remoteId,
        'contentId': value.contentId,
    };
}

