/* tslint:disable */
/* eslint-disable */
/**
 * OptProv API
 * This is the REST API to interact and control with libp2p hosts. All responses not in the HTTP status code range [200,300) return the error object below. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProvideType,
    ProvideTypeFromJSON,
    ProvideTypeFromJSONTyped,
    ProvideTypeToJSON,
} from './ProvideType';

/**
 * 
 * @export
 * @interface MonitorProviderRecordMeasurementRequest
 */
export interface MonitorProviderRecordMeasurementRequest {
    /**
     * The host to monitor for this measurement
     * @type {string}
     * @memberof MonitorProviderRecordMeasurementRequest
     */
    hostId: string;
    /**
     * 
     * @type {string}
     * @memberof MonitorProviderRecordMeasurementRequest
     */
    endAt?: string;
    /**
     * 
     * @type {string}
     * @memberof MonitorProviderRecordMeasurementRequest
     */
    measurementType: string;
    /**
     * 
     * @type {ProvideType}
     * @memberof MonitorProviderRecordMeasurementRequest
     */
    provideType: ProvideType;
}

export function MonitorProviderRecordMeasurementRequestFromJSON(json: any): MonitorProviderRecordMeasurementRequest {
    return MonitorProviderRecordMeasurementRequestFromJSONTyped(json, false);
}

export function MonitorProviderRecordMeasurementRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitorProviderRecordMeasurementRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hostId': json['hostId'],
        'endAt': !exists(json, 'endAt') ? undefined : json['endAt'],
        'measurementType': json['measurementType'],
        'provideType': ProvideTypeFromJSON(json['provideType']),
    };
}

export function MonitorProviderRecordMeasurementRequestToJSON(value?: MonitorProviderRecordMeasurementRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hostId': value.hostId,
        'endAt': value.endAt,
        'measurementType': value.measurementType,
        'provideType': ProvideTypeToJSON(value.provideType),
    };
}

