/* tslint:disable */
/* eslint-disable */
/**
 * OptProv API
 * This is the REST API to interact and control with libp2p hosts. All responses not in the HTTP status code range [200,300) return the error object below. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Provide,
    ProvideFromJSON,
    ProvideFromJSONTyped,
    ProvideToJSON,
} from './Provide';
import {
    ProvideDetailsAllOf,
    ProvideDetailsAllOfFromJSON,
    ProvideDetailsAllOfFromJSONTyped,
    ProvideDetailsAllOfToJSON,
} from './ProvideDetailsAllOf';

/**
 * 
 * @export
 * @interface ProvideDetails
 */
export interface ProvideDetails {
    /**
     * 
     * @type {number}
     * @memberof ProvideDetails
     */
    provideId: number;
    /**
     * 
     * @type {string}
     * @memberof ProvideDetails
     */
    hostId: string;
    /**
     * 
     * @type {string}
     * @memberof ProvideDetails
     */
    contentId: string;
    /**
     * 
     * @type {number}
     * @memberof ProvideDetails
     */
    initialRoutingTableId: number;
    /**
     * 
     * @type {number}
     * @memberof ProvideDetails
     */
    finalRoutingTableId: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProvideDetails
     */
    startedAt: string;
    /**
     * 
     * @type {string}
     * @memberof ProvideDetails
     */
    endedAt: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProvideDetails
     */
    error: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProvideDetails
     */
    distance: string;
    /**
     * 
     * @type {number}
     * @memberof ProvideDetails
     */
    connectionsCount: number;
    /**
     * 
     * @type {number}
     * @memberof ProvideDetails
     */
    dialsCount: number;
    /**
     * 
     * @type {number}
     * @memberof ProvideDetails
     */
    findNodesCount: number;
    /**
     * 
     * @type {number}
     * @memberof ProvideDetails
     */
    addProvidersCount: number;
}

export function ProvideDetailsFromJSON(json: any): ProvideDetails {
    return ProvideDetailsFromJSONTyped(json, false);
}

export function ProvideDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProvideDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'provideId': json['provideId'],
        'hostId': json['hostId'],
        'contentId': json['contentId'],
        'initialRoutingTableId': json['initialRoutingTableId'],
        'finalRoutingTableId': json['finalRoutingTableId'],
        'startedAt': json['startedAt'],
        'endedAt': json['endedAt'],
        'error': json['error'],
        'distance': json['distance'],
        'connectionsCount': json['connectionsCount'],
        'dialsCount': json['dialsCount'],
        'findNodesCount': json['findNodesCount'],
        'addProvidersCount': json['addProvidersCount'],
    };
}

export function ProvideDetailsToJSON(value?: ProvideDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'provideId': value.provideId,
        'hostId': value.hostId,
        'contentId': value.contentId,
        'initialRoutingTableId': value.initialRoutingTableId,
        'finalRoutingTableId': value.finalRoutingTableId,
        'startedAt': value.startedAt,
        'endedAt': value.endedAt,
        'error': value.error,
        'distance': value.distance,
        'connectionsCount': value.connectionsCount,
        'dialsCount': value.dialsCount,
        'findNodesCount': value.findNodesCount,
        'addProvidersCount': value.addProvidersCount,
    };
}

