/* tslint:disable */
/* eslint-disable */
/**
 * OptProv API
 * This is the REST API to interact and control with libp2p hosts. All responses not in the HTTP status code range [200,300) return the error object below. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateHostRequest
 */
export interface CreateHostRequest {
    /**
     * An arbitrary name for this host.
     * @type {string}
     * @memberof CreateHostRequest
     */
    name: string;
}

export function CreateHostRequestFromJSON(json: any): CreateHostRequest {
    return CreateHostRequestFromJSONTyped(json, false);
}

export function CreateHostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateHostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateHostRequestToJSON(value?: CreateHostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

